### ISSUE TITLE
Remove trailing slashes for FURLs

### ISSUE THREAD

**Issue by christianseel** [modxcms/Discuss#10]
URLs in discuss describe mostly files (threads), so I wouldn't use trailing slashes. What do you think?

I guess only L490 needs to be changed:
https://github.com/modxcms/Discuss/blob/develop/core/components/discuss/model/discuss/request/disrequest.class.php#L490

`$url = $this->modx->getOption('site_url',null,MODX_SITE_URL).trim($url,'/');`

**Comment by the-dunnock** [comment]
Fixed into git, required just trailing slash removal

**Comment by the-dunnock** [comment]
Whops, wrong ticket

**Comment by the-dunnock** [comment]
And I am bad with commit messages still
