### ISSUE TITLE
URL in notification email is not "friendly"

### ISSUE THREAD

**Issue by christianseel** [modxcms/Discuss#12]
URLs generated in the notification mail are no FURLs:
domain.com/forum/thread//?thread=6466&page=2#dis-post-35937

A Placeholder for an "unsubscribe" URL would also be great! (URL to the thread with "?unsubscribe=1").

(Using Discuss 1.2.2.)

**Comment by the-dunnock** [comment]
Friendly now :)

Git commit: https://github.com/modxcms/Discuss/commit/6ca7e937588a48febae3b102abb6feec121c3c86
