### ISSUE TITLE
Empty 2nd thread page (pagination)

### ISSUE THREAD

**Issue by christianseel** [modxcms/Discuss#13]
Since using 1.2.2 discuss shows the pagination even if there is nothing to display on the next page...

example: http://de.modx.com/forum/thread/6466/categories-manager-schreibt-keinen-daten-in-spalte-rank

**Comment by the-dunnock** [comment]
Hmmm... seems that I cannot reproduce it.

Thread with ten posts : http://luggage.dunnock.modxcloud.com/thread/2/second-test-with-only-ten-posts/ no pagination and one with 11 posts goes like it should to second page http://luggage.dunnock.modxcloud.com/thread/1/pagination-test/

I'll delve into it today with all the others for sure

**Comment by the-dunnock** [comment]
Could be that there is replies count mismatch within the threads table.

You can run next SQL statement to fix the replies count

`UPDATE modx_discuss_threads t SET replies = (SELECT (COUNT(p.id) - 1) FROM modx_discuss_posts p WHERE p.thread = t.id);`

**Comment by christianseel** [comment]
Wow! Thanks! That fixed it... :+1:

**Comment by the-dunnock** [comment]
Great news!! To be honest, it was bit shot in the dark and am glad it worked.

I'm looking at the other tickets also. Just trying to get my own site finished :)

**Comment by christianseel** [comment]
I'm now on holidays for 1 week, so no panic.
But we (german ambassadors) want to relaunch the website incl. forum on august 22nd.
