### ISSUE TITLE
No BB code support

### ISSUE THREAD

**Issue by Nuan8** [modxcms/Discuss#21]
I hope I am using the right terminology here. I installed Discuss recently and have been working to set everything up.

It turns out that the buttons in the reply/new thread text box (like bold, italics, and so on) do not work right out of the box. So it seems there is a problem with the BB code parser.

In the system settings it is set to use the disBBCodeParser, so I don't know what the problem is. The very next item in the settings is the parser class path, and this value is empty. I am hoping to fix the problem by entering the right value for this setting, but so far no love.

This is a pretty big bug in my view, I haven't found anything about it in the documentation or in the forums.

**Comment by christianseel** [comment]
The form buttons for bb-code are only working if you include the JS code. You might need to include the JS function manually.

**Comment by Nuan8** [comment]
Ah cheers, I didn't think about that. Thank you for the feedback, its quite useful.

If I may ask, can I just download the bbcode.js, upload it to the server, and put the link in the head of the wrapper? I see MODX only uses a couple of scripts, including LABjs, so I assume the LABjs handles the bbcode js file.

**Comment by Nuan8** [comment]
Ok I got it now, will put the detailed solution in the modx forums. Thanks again Christian, your info was exactly what I needed. Never would have found the solution otherwise. Cheers!

**Comment by Nuan8** [comment]
Ok this is a bug, the function is in there but doesn't work for some reason. Strangely, it works fine in Opera, but that's it.

**Comment by Nuan8** [comment]
And there must be a similar bug for the collapse function to close a section of the forum, which also only works in Opera.

**Comment by Nuan8** [comment]
Solved! Jquery wasn't loading in chromium and firefox (but was in Opera) because of this line in the LAB js loader (in the footer of wrapper.tpl):
      .script("http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js").wait()
and works fine just by removing http:, like so:
      .script("//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js").wait()

I would close this issue if I knew how...
