### ISSUE TITLE
Is this extra being maintained?  I am looking for a forum solution

### ISSUE THREAD

**Issue by sonicpunk** [modxcms/Discuss#36]
I have the feeling that this project is no longer being developed.  Is this true?  I need a forum solution for MODX that is easy to implement.  Anyone have any suggestions?

Cheers,
Ben

**Comment by rthrash** [comment]
I would consider Vanilla Forums with a SSO connector to MODX users. Would that work for you?

**Comment by Nuan8** [comment]
Discuss is not being developed, but it is a full-featured forum.

Vanilla is infinitely easier to get started with. In exchange you give up some level of control. If ease of implementation is your biggest factor, then Ryan's suggestion is probably the best option.

**Comment by sonicpunk** [comment]
Thanks for the input guys.  Then I will look at Vanilla!

**Comment by HarveyEV** [comment]
Definitely _not_ free. Get what you pay for I s’pose.

**Comment by sonicpunk** [comment]
What is wrong with the open source version of it?  Why wouldn't I use that?

**Comment by rthrash** [comment]
I think you'd be fine using that.

**Comment by HarveyEV** [comment]
Yeah, I missed the free version. If you have a premise, you should be gtg. Im’ a clouder, so not an option for me.
